### ISSUE TITLE
Team TA - Week 1: Create Jira account.

### ISSUE THREAD

**Issue by UsamaHam** [CubeStatistica/Professional-Training-for-Data-Science-Team-Underdogs#6]

**Comment by UsamaHam** [comment]
- [x] @UsamaHam 
- [x] @FaizaNaz00 
- [x] @zonishmasood 
- [ ] @mhwahla 
- [x] @farrukhhussai 
- [x] @muneeb14khan

**Comment by farrukhhussai** [comment]
https://farrukhhussain.atlassian.net/

**Comment by zonishmasood** [comment]
https://zonishmasood.atlassian.net/
